src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;


    #[ORM\Column(length: 5000, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?int $Status = null;

    #[ORM\Column(nullable: true)]
    private ?int $Listing = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Type $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->Status;
    }

    public function setStatus(?int $Status): static
    {
        $this->Status = $Status;

        return $this;
    }

    public function getListing(): ?int
    {
        return $this->Listing;
    }

    public function setListing(?int $Listing): static
    {
        $this->Listing = $Listing;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('Status')
            ->add('submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;


use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/articles')]
final class ArticleController extends AbstractController
{
    //afficher tous les articles
    #[Route('/', name: 'Articles', methods: 'GET')]
    public function index(ArticleRepository $articlerepo)
    {
        $articles = $articlerepo->findBy(['createdAt'], ['DESC']);
        //$articles = $articlerepo->findBy (['article' => $article]);

        
        return $this->render('articles/index.html.twig', [
            'articles' => $articles
        ]);
    }
// afficher les articles par leur ID
    #[Route('/show/{id}', name: "article_show", methods: 'GET')]
    public function show(ArticleRepository $ArticleRepository, int $id)
    {
        $article = $ArticleRepository->findOneBy(['id' => $id]);
        return $this->render('articles/articleshow.html.twig', [
            'article' => $article
        ]);
    }

   
    #[Route('/new', name: 'article_new')]
    public function new(Request $REQUEST, EntityManagerInterface $em)
    {
        
        $article = new Article();

        $formArticle = $this->createForm(ArticleType::class, $article);
        
        $formArticle->handleRequest($REQUEST);
       
        if ($formArticle->isSubmitted() && $formArticle->isValid()) {
            //comment avoir la date immutable de now
            $date = new DateTimeImmutable();
            $article->setCreatedAt($date);
            //ajouter la date dans mon article que je viens de creer

            // dd($date, $article);
            $em->persist($article);
            
            $em->flush();   

            $this->addFlash('success', 'bravo votre article a ete créé');
            
           
            return $this->redirectToRoute('Articles');
        }
        //renvoie le formulaire à la view (url)
        return $this->render('articles/articlenew.html.twig', [

            'formArticle' => $formArticle
        ]);

    }

    #[Route('/delete/{id}', name: 'article_delete')]
    public function delete(int $id, Request $request, Article $article, EntityManagerInterface $em)
    {

        if ($this->isCsrfTokenValid('delete' . $id, $request->request->get('_token'))) {
            $em->remove($article);
            $em->flush();
             $this->addFlash('success', 'bravo votre article a ete supprimé');

            return $this->redirectToRoute('Articles');
        } else {
            $this->addFlash('error','echec de la suppression');
            return$this->redirectToRoute('Articles');
          
        }
    }


    #[Route('/{id}/edit', name: 'article_edit')]
   
    public function edit(Article $article, Request $request, EntityManagerInterface $em)
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            $this->addFlash('success', 'bravo votre article a ete modifié');
            return $this->redirectToRoute('Articles');
        }
        return $this->render('articles/edit.html.twig', [
            'form' => $form

        ]);

    }
}

templates/articles/article_edit.html.twig
{{ form(form)}}

templates/articles/articlenew.html.twig
{{ form(formArticle)}}

templates/articles/articleshow.html.twig
<h1>{{article.title}}</h1>
<p>{{article.content}}</p>

<a href="{{ path('Articles') }}">Retour</a>.

{% include "articles/delete_form.html.twig" %}

templates/articles/delete_form.html.twig
<form
  action="{{ path('article_delete', { id: article.id }) }}"
  method="POST"
  onsubmit="return confirm ('es tu sûr de vouloir supprimer cet article?');"
>
  <input
    type="hidden"
    name="_token"
    value="{{ csrf_token('delete'~ article.id)}}"
  />

  <input type="submit" value="supprimer" />
</form>

templates/articles/edit.html.twig
{{form(form)}}

templates/articles/index.html.twig
{% extends "base.html.twig" %} {% block body %}
<section class="index_twig">

  {% for label, messages in app.flashes %}
  {% for message in messages %}
  <div>
      {{message}}
  </div>
  {% endfor %}
  {% endfor %}


  <h1>Liste des articles</h1>
  
  <a class="new-article" href={{path('article_new')}}>Ajouter article</a>

{% for article in articles %}
  <article class="article">|
    <div class="index_fields">
    <h2>{{ article.title }}</h2>
    <p>{{ article.content }}</p>
    <span>{{ article.status }}</span>
    <p>{{ article.createdAt|date("m/d/Y H:i") }}</p>
    </div>
 
    <div class="index_links">
    <a href="{{ path('article_show', {id: article.id}) }}">Lire</a>
    <a href="{{ path('article_edit', {id: article.id}) }}">Modifier</a>
    {% include "articles/delete_form.html.twig" %}
    </div>
  </article>
</section>
{% endfor %} 

{% endblock %}